server:
  port: 8094
  
Spring:
  application:
    name: SpringTest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    maxActive: 10
    initialSize: 5
    maxWait: 1000
    hikari:
      maximumPoolSize: 20 
      idleTimeout: 200
      connectionTimeout: 30000
  
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #database: MYSQL
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: update      